"""create settlement table

Revision ID: 5677157129a0
Revises: c4b2d6a5c8f1
Create Date: 2026-03-12 17:02:50.982274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5677157129a0'
down_revision: Union[str, None] = 'c4b2d6a5c8f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trade_settlements', 'order_count',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='包含的订单笔数',
               existing_nullable=False)
    op.alter_column('trade_settlements', 'total_amount',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               server_default=None,
               existing_comment='订单总额 (元)',
               existing_nullable=False)
    op.alter_column('trade_settlements', 'platform_fee',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               server_default=None,
               existing_comment='平台抽成 (元)',
               existing_nullable=False)
    op.alter_column('trade_settlements', 'settle_amount',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               server_default=None,
               existing_comment='应结算金额 (元)',
               existing_nullable=False)
    op.alter_column('trade_settlements', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='打款状态 (0-待打款, 1-已打款)',
               existing_nullable=False)
    op.alter_column('trade_settlements', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('trade_settlements', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='最后更新时间',
               existing_nullable=False)
    op.drop_index('uq_trade_settlements_settle_date', table_name='trade_settlements')
    op.create_index(op.f('ix_trade_settlements_settle_date'), 'trade_settlements', ['settle_date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_settlements_settle_date'), table_name='trade_settlements')
    op.create_index('uq_trade_settlements_settle_date', 'trade_settlements', ['settle_date'], unique=False)
    op.alter_column('trade_settlements', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='最后更新时间',
               existing_nullable=False)
    op.alter_column('trade_settlements', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('trade_settlements', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'0'"),
               existing_comment='打款状态 (0-待打款, 1-已打款)',
               existing_nullable=False)
    op.alter_column('trade_settlements', 'settle_amount',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               server_default=sa.text("'0.00'"),
               existing_comment='应结算金额 (元)',
               existing_nullable=False)
    op.alter_column('trade_settlements', 'platform_fee',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               server_default=sa.text("'0.00'"),
               existing_comment='平台抽成 (元)',
               existing_nullable=False)
    op.alter_column('trade_settlements', 'total_amount',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               server_default=sa.text("'0.00'"),
               existing_comment='订单总额 (元)',
               existing_nullable=False)
    op.alter_column('trade_settlements', 'order_count',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'0'"),
               existing_comment='包含的订单笔数',
               existing_nullable=False)
    # ### end Alembic commands ###
