"""empty message

Revision ID: 981a6e580a29
Revises: 
Create Date: 2026-02-28 10:48:18.285317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '981a6e580a29'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('busi_price_templates',
    sa.Column('operator_id', sa.Integer(), nullable=False, comment='所属运营商ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='模板名称'),
    sa.Column('rules_json', sa.Text(), nullable=False, comment='计费规则 (JSON格式)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='最后更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='逻辑删除标记'),
    sa.ForeignKeyConstraint(['operator_id'], ['sys_operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_busi_price_templates_is_deleted'), 'busi_price_templates', ['is_deleted'], unique=False)
    op.create_table('mkt_coupons',
    sa.Column('operator_id', sa.Integer(), nullable=True, comment='所属运营商ID (空则为平台券)'),
    sa.Column('type', sa.String(length=50), nullable=False, comment="优惠券类型 (例如: 'discount'-折扣, 'cash'-代金券)"),
    sa.Column('discount_val', sa.Numeric(precision=10, scale=2), nullable=False, comment='折扣或金额值'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='最后更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='逻辑删除标记'),
    sa.ForeignKeyConstraint(['operator_id'], ['sys_operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mkt_coupons_is_deleted'), 'mkt_coupons', ['is_deleted'], unique=False)
    op.create_table('trade_invoices',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='申请用户ID'),
    sa.Column('operator_id', sa.Integer(), nullable=False, comment='开票运营商ID'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='发票金额'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='接收邮箱'),
    sa.Column('status', sa.Integer(), nullable=False, comment='开票状态 (例如: 0-申请中, 1-已开票, 2-失败)'),
    sa.Column('file_url', sa.String(length=255), nullable=True, comment='发票文件URL'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='最后更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='逻辑删除标记'),
    sa.ForeignKeyConstraint(['operator_id'], ['sys_operators.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_invoices_is_deleted'), 'trade_invoices', ['is_deleted'], unique=False)
    op.create_table('busi_user_fleet_association',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('fleet_id', sa.Integer(), nullable=False, comment='车队ID'),
    sa.ForeignKeyConstraint(['fleet_id'], ['busi_fleets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'fleet_id')
    )
    op.create_table('eq_stations',
    sa.Column('operator_id', sa.Integer(), nullable=False, comment='所属运营商ID'),
    sa.Column('template_id', sa.Integer(), nullable=True, comment='计费模板ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='充电站名称'),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False, comment='经度'),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False, comment='纬度'),
    sa.Column('status', sa.Integer(), nullable=False, comment='充电站状态 (例如: 0-运营, 1-建设中, 2-关闭)'),
    sa.Column('visibility', sa.String(length=20), nullable=False, comment='可见性 (public/private)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='最后更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='逻辑删除标记'),
    sa.ForeignKeyConstraint(['operator_id'], ['sys_operators.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['busi_price_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eq_stations_is_deleted'), 'eq_stations', ['is_deleted'], unique=False)
    op.create_table('mkt_user_coupons',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('coupon_id', sa.Integer(), nullable=False, comment='优惠券ID'),
    sa.Column('status', sa.Integer(), nullable=False, comment='使用状态 (例如: 0-未使用, 1-已使用, 2-已过期)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='最后更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='逻辑删除标记'),
    sa.ForeignKeyConstraint(['coupon_id'], ['mkt_coupons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mkt_user_coupons_is_deleted'), 'mkt_user_coupons', ['is_deleted'], unique=False)
    op.create_table('eq_chargers',
    sa.Column('station_id', sa.Integer(), nullable=False, comment='所属充电站ID'),
    sa.Column('sn_code', sa.String(length=50), nullable=False, comment='充电桩序列号 (唯一)'),
    sa.Column('type', sa.String(length=20), nullable=False, comment="充电桩类型 (例如: 'AC'-交流, 'DC'-直流)"),
    sa.Column('status', sa.Integer(), nullable=False, comment='充电桩状态 (例如: 0-空闲, 1-充电中, 2-故障)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='最后更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='逻辑删除标记'),
    sa.ForeignKeyConstraint(['station_id'], ['eq_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eq_chargers_is_deleted'), 'eq_chargers', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_eq_chargers_sn_code'), 'eq_chargers', ['sn_code'], unique=True)
    op.create_table('trade_orders',
    sa.Column('order_no', sa.String(length=64), nullable=False, comment='订单号 (唯一)'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('charger_id', sa.Integer(), nullable=False, comment='充电桩ID'),
    sa.Column('operator_id', sa.Integer(), nullable=False, comment='运营商ID'),
    sa.Column('start_time', sa.DateTime(), nullable=False, comment='充电开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='充电结束时间'),
    sa.Column('total_kwh', sa.Numeric(precision=10, scale=2), nullable=False, comment='总充电度数 (kWh)'),
    sa.Column('ele_fee', sa.Numeric(precision=10, scale=2), nullable=False, comment='电费 (元)'),
    sa.Column('service_fee', sa.Numeric(precision=10, scale=2), nullable=False, comment='服务费 (元)'),
    sa.Column('total_fee', sa.Numeric(precision=10, scale=2), nullable=False, comment='总费用 (元)'),
    sa.Column('status', sa.Integer(), nullable=False, comment='订单状态 (例如: 0-进行中, 1-已完成, 2-异常)'),
    sa.Column('settle_status', sa.Integer(), nullable=False, comment='结算状态 (例如: 0-未结算, 1-已结算)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='最后更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='逻辑删除标记'),
    sa.ForeignKeyConstraint(['charger_id'], ['eq_chargers.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['sys_operators.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_orders_is_deleted'), 'trade_orders', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_trade_orders_order_no'), 'trade_orders', ['order_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_orders_order_no'), table_name='trade_orders')
    op.drop_index(op.f('ix_trade_orders_is_deleted'), table_name='trade_orders')
    op.drop_table('trade_orders')
    op.drop_index(op.f('ix_eq_chargers_sn_code'), table_name='eq_chargers')
    op.drop_index(op.f('ix_eq_chargers_is_deleted'), table_name='eq_chargers')
    op.drop_table('eq_chargers')
    op.drop_index(op.f('ix_mkt_user_coupons_is_deleted'), table_name='mkt_user_coupons')
    op.drop_table('mkt_user_coupons')
    op.drop_index(op.f('ix_eq_stations_is_deleted'), table_name='eq_stations')
    op.drop_table('eq_stations')
    op.drop_table('busi_user_fleet_association')
    op.drop_index(op.f('ix_trade_invoices_is_deleted'), table_name='trade_invoices')
    op.drop_table('trade_invoices')
    op.drop_index(op.f('ix_mkt_coupons_is_deleted'), table_name='mkt_coupons')
    op.drop_table('mkt_coupons')
    op.drop_index(op.f('ix_busi_price_templates_is_deleted'), table_name='busi_price_templates')
    op.drop_table('busi_price_templates')
    # ### end Alembic commands ###
