"""orders

Revision ID: ae8d07e02c9b
Revises: a1c9f43b7d21
Create Date: 2026-04-01 10:12:56.784394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ae8d07e02c9b'
down_revision: Union[str, None] = 'a1c9f43b7d21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('busi_fleets', 'is_whitelist',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否白名单车队',
               existing_comment='是否为白名单车队',
               existing_nullable=False)
    op.alter_column('busi_price_templates', 'rules_json',
               existing_type=mysql.TEXT(),
               comment='计费规则JSON',
               existing_comment='计费规则 (JSON格式)',
               existing_nullable=False)
    op.alter_column('eq_chargers', 'sn_code',
               existing_type=mysql.VARCHAR(length=50),
               comment='充电桩序列号',
               existing_comment='充电桩序列号 (唯一)',
               existing_nullable=False)
    op.alter_column('eq_chargers', 'type',
               existing_type=mysql.VARCHAR(length=20),
               comment='充电桩类型',
               existing_comment="充电桩类型 (例如: 'AC'-交流, 'DC'-直流)",
               existing_nullable=False)
    op.alter_column('eq_chargers', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               comment='充电桩状态',
               existing_comment='充电桩状态 (例如: 0-空闲, 1-充电中, 2-故障)',
               existing_nullable=False)
    op.alter_column('eq_stations', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               comment='充电站状态',
               existing_comment='充电站状态 (例如: 0-运营, 1-建设中, 2-关闭)',
               existing_nullable=False)
    op.alter_column('eq_stations', 'visibility',
               existing_type=mysql.VARCHAR(length=20),
               comment='可见性',
               existing_comment='可见性 (public/private)',
               existing_nullable=False)
    op.alter_column('mkt_coupons', 'operator_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='所属运营商ID',
               existing_comment='所属运营商ID (空则为平台券)',
               existing_nullable=True)
    op.alter_column('mkt_coupons', 'type',
               existing_type=mysql.VARCHAR(length=50),
               comment='优惠券类型',
               existing_comment="优惠券类型 (例如: 'discount'-折扣, 'cash'-代金券)",
               existing_nullable=False)
    op.alter_column('mkt_coupons', 'discount_val',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='优惠值',
               existing_comment='折扣或金额值',
               existing_nullable=False)
    op.alter_column('mkt_user_coupons', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               comment='使用状态',
               existing_comment='使用状态 (例如: 0-未使用, 1-已使用, 2-已过期)',
               existing_nullable=False)
    op.alter_column('sys_operators', 'org_type',
               existing_type=mysql.VARCHAR(length=50),
               comment='组织类型',
               existing_comment="组织类型 (例如: '企业', '个人')",
               existing_nullable=False)
    op.alter_column('sys_operators', 'license_url',
               existing_type=mysql.VARCHAR(length=255),
               comment='营业执照URL',
               existing_comment='营业执照图片URL',
               existing_nullable=True)
    op.alter_column('sys_users', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               comment='手机号',
               existing_comment='手机号 (唯一)',
               existing_nullable=False)
    op.alter_column('sys_users', 'password_hash',
               existing_type=mysql.VARCHAR(length=255),
               comment='密码哈希',
               existing_comment='哈希后的密码',
               existing_nullable=False)
    op.alter_column('sys_users', 'vin_code',
               existing_type=mysql.VARCHAR(length=50),
               comment='车辆VIN',
               existing_comment='车辆识别码 (VIN)',
               existing_nullable=True)
    op.alter_column('sys_users', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               comment='用户状态',
               existing_comment='用户状态 (例如: 0-正常, 1-禁用)',
               existing_nullable=False)
    op.alter_column('sys_users', 'role',
               existing_type=mysql.VARCHAR(length=20),
               comment='用户角色',
               existing_comment='用户角色 (admin/operator/user)',
               existing_nullable=False)
    op.alter_column('trade_invoices', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               comment='发票状态',
               existing_comment='开票状态 (例如: 0-申请中, 1-已开票, 2-失败)',
               existing_nullable=False)
    op.alter_column('trade_orders', 'order_no',
               existing_type=mysql.VARCHAR(length=64),
               comment='订单号',
               existing_comment='订单号 (唯一)',
               existing_nullable=False)
    op.alter_column('trade_orders', 'start_time',
               existing_type=mysql.DATETIME(),
               comment='开始充电时间',
               existing_comment='充电开始时间',
               existing_nullable=False)
    op.alter_column('trade_orders', 'end_time',
               existing_type=mysql.DATETIME(),
               comment='结束充电时间',
               existing_comment='充电结束时间',
               existing_nullable=True)
    op.alter_column('trade_orders', 'total_kwh',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='充电量(kWh)',
               existing_comment='总充电度数 (kWh)',
               existing_nullable=False)
    op.alter_column('trade_orders', 'ele_fee',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='电费',
               existing_comment='电费 (元)',
               existing_nullable=False)
    op.alter_column('trade_orders', 'service_fee',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='服务费',
               existing_comment='服务费 (元)',
               existing_nullable=False)
    op.alter_column('trade_orders', 'total_fee',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='总金额',
               existing_comment='总费用 (元)',
               existing_nullable=False)
    op.alter_column('trade_orders', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               comment='订单状态 0-charging 1-completed 2-abnormal',
               existing_comment='订单状态 (例如: 0-进行中, 1-已完成, 2-异常)',
               existing_nullable=False)
    op.alter_column('trade_orders', 'settle_status',
               existing_type=mysql.INTEGER(display_width=11),
               comment='结算状态',
               existing_comment='结算状态 (例如: 0-未结算, 1-已结算)',
               existing_nullable=False)
    op.alter_column('trade_settlements', 'settle_date',
               existing_type=sa.DATE(),
               comment='清分日期',
               existing_comment='结算日期 (即 T 日)',
               existing_nullable=False)
    op.alter_column('trade_settlements', 'order_count',
               existing_type=mysql.INTEGER(display_width=11),
               comment='订单数量',
               existing_comment='包含的订单笔数',
               existing_nullable=False)
    op.alter_column('trade_settlements', 'total_amount',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               comment='订单总金额',
               existing_comment='订单总额 (元)',
               existing_nullable=False)
    op.alter_column('trade_settlements', 'platform_fee',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               comment='平台抽成',
               existing_comment='平台抽成 (元)',
               existing_nullable=False)
    op.alter_column('trade_settlements', 'settle_amount',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               comment='应结金额',
               existing_comment='应结算金额 (元)',
               existing_nullable=False)
    op.alter_column('trade_settlements', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               comment='打款状态',
               existing_comment='打款状态 (0-待打款, 1-已打款)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trade_settlements', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               comment='打款状态 (0-待打款, 1-已打款)',
               existing_comment='打款状态',
               existing_nullable=False)
    op.alter_column('trade_settlements', 'settle_amount',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               comment='应结算金额 (元)',
               existing_comment='应结金额',
               existing_nullable=False)
    op.alter_column('trade_settlements', 'platform_fee',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               comment='平台抽成 (元)',
               existing_comment='平台抽成',
               existing_nullable=False)
    op.alter_column('trade_settlements', 'total_amount',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               comment='订单总额 (元)',
               existing_comment='订单总金额',
               existing_nullable=False)
    op.alter_column('trade_settlements', 'order_count',
               existing_type=mysql.INTEGER(display_width=11),
               comment='包含的订单笔数',
               existing_comment='订单数量',
               existing_nullable=False)
    op.alter_column('trade_settlements', 'settle_date',
               existing_type=sa.DATE(),
               comment='结算日期 (即 T 日)',
               existing_comment='清分日期',
               existing_nullable=False)
    op.alter_column('trade_orders', 'settle_status',
               existing_type=mysql.INTEGER(display_width=11),
               comment='结算状态 (例如: 0-未结算, 1-已结算)',
               existing_comment='结算状态',
               existing_nullable=False)
    op.alter_column('trade_orders', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               comment='订单状态 (例如: 0-进行中, 1-已完成, 2-异常)',
               existing_comment='订单状态 0-charging 1-completed 2-abnormal',
               existing_nullable=False)
    op.alter_column('trade_orders', 'total_fee',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='总费用 (元)',
               existing_comment='总金额',
               existing_nullable=False)
    op.alter_column('trade_orders', 'service_fee',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='服务费 (元)',
               existing_comment='服务费',
               existing_nullable=False)
    op.alter_column('trade_orders', 'ele_fee',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='电费 (元)',
               existing_comment='电费',
               existing_nullable=False)
    op.alter_column('trade_orders', 'total_kwh',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='总充电度数 (kWh)',
               existing_comment='充电量(kWh)',
               existing_nullable=False)
    op.alter_column('trade_orders', 'end_time',
               existing_type=mysql.DATETIME(),
               comment='充电结束时间',
               existing_comment='结束充电时间',
               existing_nullable=True)
    op.alter_column('trade_orders', 'start_time',
               existing_type=mysql.DATETIME(),
               comment='充电开始时间',
               existing_comment='开始充电时间',
               existing_nullable=False)
    op.alter_column('trade_orders', 'order_no',
               existing_type=mysql.VARCHAR(length=64),
               comment='订单号 (唯一)',
               existing_comment='订单号',
               existing_nullable=False)
    op.alter_column('trade_invoices', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               comment='开票状态 (例如: 0-申请中, 1-已开票, 2-失败)',
               existing_comment='发票状态',
               existing_nullable=False)
    op.alter_column('sys_users', 'role',
               existing_type=mysql.VARCHAR(length=20),
               comment='用户角色 (admin/operator/user)',
               existing_comment='用户角色',
               existing_nullable=False)
    op.alter_column('sys_users', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               comment='用户状态 (例如: 0-正常, 1-禁用)',
               existing_comment='用户状态',
               existing_nullable=False)
    op.alter_column('sys_users', 'vin_code',
               existing_type=mysql.VARCHAR(length=50),
               comment='车辆识别码 (VIN)',
               existing_comment='车辆VIN',
               existing_nullable=True)
    op.alter_column('sys_users', 'password_hash',
               existing_type=mysql.VARCHAR(length=255),
               comment='哈希后的密码',
               existing_comment='密码哈希',
               existing_nullable=False)
    op.alter_column('sys_users', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               comment='手机号 (唯一)',
               existing_comment='手机号',
               existing_nullable=False)
    op.alter_column('sys_operators', 'license_url',
               existing_type=mysql.VARCHAR(length=255),
               comment='营业执照图片URL',
               existing_comment='营业执照URL',
               existing_nullable=True)
    op.alter_column('sys_operators', 'org_type',
               existing_type=mysql.VARCHAR(length=50),
               comment="组织类型 (例如: '企业', '个人')",
               existing_comment='组织类型',
               existing_nullable=False)
    op.alter_column('mkt_user_coupons', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               comment='使用状态 (例如: 0-未使用, 1-已使用, 2-已过期)',
               existing_comment='使用状态',
               existing_nullable=False)
    op.alter_column('mkt_coupons', 'discount_val',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='折扣或金额值',
               existing_comment='优惠值',
               existing_nullable=False)
    op.alter_column('mkt_coupons', 'type',
               existing_type=mysql.VARCHAR(length=50),
               comment="优惠券类型 (例如: 'discount'-折扣, 'cash'-代金券)",
               existing_comment='优惠券类型',
               existing_nullable=False)
    op.alter_column('mkt_coupons', 'operator_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='所属运营商ID (空则为平台券)',
               existing_comment='所属运营商ID',
               existing_nullable=True)
    op.alter_column('eq_stations', 'visibility',
               existing_type=mysql.VARCHAR(length=20),
               comment='可见性 (public/private)',
               existing_comment='可见性',
               existing_nullable=False)
    op.alter_column('eq_stations', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               comment='充电站状态 (例如: 0-运营, 1-建设中, 2-关闭)',
               existing_comment='充电站状态',
               existing_nullable=False)
    op.alter_column('eq_chargers', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               comment='充电桩状态 (例如: 0-空闲, 1-充电中, 2-故障)',
               existing_comment='充电桩状态',
               existing_nullable=False)
    op.alter_column('eq_chargers', 'type',
               existing_type=mysql.VARCHAR(length=20),
               comment="充电桩类型 (例如: 'AC'-交流, 'DC'-直流)",
               existing_comment='充电桩类型',
               existing_nullable=False)
    op.alter_column('eq_chargers', 'sn_code',
               existing_type=mysql.VARCHAR(length=50),
               comment='充电桩序列号 (唯一)',
               existing_comment='充电桩序列号',
               existing_nullable=False)
    op.alter_column('busi_price_templates', 'rules_json',
               existing_type=mysql.TEXT(),
               comment='计费规则 (JSON格式)',
               existing_comment='计费规则JSON',
               existing_nullable=False)
    op.alter_column('busi_fleets', 'is_whitelist',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否为白名单车队',
               existing_comment='是否白名单车队',
               existing_nullable=False)
    # ### end Alembic commands ###
